name: 🐍 Generate Contributions Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Generate GitHub Contribution Snake
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mr-uzairr
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 3: Set up Git for pushing to 'output' branch
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 4: Create 'output' branch if it doesn't exist
      - name: Create output branch if it doesn't exist
        run: |
          git checkout --orphan output  # Create an orphan branch 'output'
          git rm -rf .  # Remove all files from the index
          git commit --allow-empty -m "Initial commit on output branch"
          git push --set-upstream origin output  # Push to GitHub

      # Step 5: Add and commit the new SVGs to the 'output' branch
      - name: Commit and push the generated files
        run: |
          git add dist/*  # Add all files in the 'dist' folder
          git commit -m "Update contribution snake"
          git push origin output --force  # Push to the 'output' branch

      # Step 6: Deploy to GitHub Pages using crazy-max action
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # The branch where GitHub Pages is served from
          build_dir: dist  # Directory containing the files to deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use your GitHub Personal Access Token
