name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *' # runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    name: Generate Snake SVG
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
